//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 04:37:44 PM CDT 
//


package com.allflex.api.flexspec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Index" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ProductLine" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Silhouette" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Outline" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Faces">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Face">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Variables">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Variable" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Index" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                 &lt;element name="Role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="PositionX" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="PositionY" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                                 &lt;element name="ValueFormat" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                                 &lt;element name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="FontSize" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="IsFixed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                                 &lt;element name="IsLaser" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                                                 &lt;element name="IsInk" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                                 &lt;element name="LogoImageLocation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                                 &lt;element name="Radius" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                                 &lt;element name="CurveTextAttachTo" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                                 &lt;element name="CopyValueFrom" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Colors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Color" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ColorCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="HexCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "index",
    "name",
    "description",
    "productLine",
    "silhouette",
    "outline",
    "color",
    "faces",
    "colors"
})
public class Component {

    @XmlElement(name = "Index", required = true)
    protected Object index;
    @XmlElement(name = "Name", required = true)
    protected Object name;
    @XmlElement(name = "Description")
    protected Object description;
    @XmlElement(name = "ProductLine")
    protected Object productLine;
    @XmlElement(name = "Silhouette")
    protected Object silhouette;
    @XmlElement(name = "Outline")
    protected Object outline;
    @XmlElement(name = "Color")
    protected Object color;
    @XmlElement(name = "Faces", required = true)
    protected Faces faces;
    @XmlElement(name = "Colors", required = true)
    protected Colors colors;

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIndex(Object value) {
        this.index = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setName(Object value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDescription(Object value) {
        this.description = value;
    }

    /**
     * Gets the value of the productLine property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProductLine() {
        return productLine;
    }

    /**
     * Sets the value of the productLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProductLine(Object value) {
        this.productLine = value;
    }

    /**
     * Gets the value of the silhouette property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSilhouette() {
        return silhouette;
    }

    /**
     * Sets the value of the silhouette property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSilhouette(Object value) {
        this.silhouette = value;
    }

    /**
     * Gets the value of the outline property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOutline() {
        return outline;
    }

    /**
     * Sets the value of the outline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOutline(Object value) {
        this.outline = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setColor(Object value) {
        this.color = value;
    }

    /**
     * Gets the value of the faces property.
     * 
     * @return
     *     possible object is
     *     {@link Faces }
     *     
     */
    public Faces getFaces() {
        return faces;
    }

    /**
     * Sets the value of the faces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Faces }
     *     
     */
    public void setFaces(Faces value) {
        this.faces = value;
    }

    /**
     * Gets the value of the colors property.
     * 
     * @return
     *     possible object is
     *     {@link Colors }
     *     
     */
    public Colors getColors() {
        return colors;
    }

    /**
     * Sets the value of the colors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Colors }
     *     
     */
    public void setColors(Colors value) {
        this.colors = value;
    }

}
