//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.26 at 08:41:00 PM CDT 
//


package com.allflex.api.flexspec;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.allflex.api.flexspec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.allflex.api.flexspec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.Specification }
     * 
     */
    public Document.Specification createDocumentSpecification() {
        return new Document.Specification();
    }

    /**
     * Create an instance of {@link Document.Specification.Components }
     * 
     */
    public Document.Specification.Components createDocumentSpecificationComponents() {
        return new Document.Specification.Components();
    }

    /**
     * Create an instance of {@link Document.Specification.Components.Component }
     * 
     */
    public Document.Specification.Components.Component createDocumentSpecificationComponentsComponent() {
        return new Document.Specification.Components.Component();
    }

    /**
     * Create an instance of {@link Document.Specification.Components.Component.Colors }
     * 
     */
    public Document.Specification.Components.Component.Colors createDocumentSpecificationComponentsComponentColors() {
        return new Document.Specification.Components.Component.Colors();
    }

    /**
     * Create an instance of {@link Document.Specification.Components.Component.Faces }
     * 
     */
    public Document.Specification.Components.Component.Faces createDocumentSpecificationComponentsComponentFaces() {
        return new Document.Specification.Components.Component.Faces();
    }

    /**
     * Create an instance of {@link Document.Specification.Components.Component.Faces.Face }
     * 
     */
    public Document.Specification.Components.Component.Faces.Face createDocumentSpecificationComponentsComponentFacesFace() {
        return new Document.Specification.Components.Component.Faces.Face();
    }

    /**
     * Create an instance of {@link Document.Specification.Components.Component.Faces.Face.Variables }
     * 
     */
    public Document.Specification.Components.Component.Faces.Face.Variables createDocumentSpecificationComponentsComponentFacesFaceVariables() {
        return new Document.Specification.Components.Component.Faces.Face.Variables();
    }

    /**
     * Create an instance of {@link Document.Specification.Components.Component.Colors.Color }
     * 
     */
    public Document.Specification.Components.Component.Colors.Color createDocumentSpecificationComponentsComponentColorsColor() {
        return new Document.Specification.Components.Component.Colors.Color();
    }

    /**
     * Create an instance of {@link Document.Specification.Components.Component.Faces.Face.Variables.Variable }
     * 
     */
    public Document.Specification.Components.Component.Faces.Face.Variables.Variable createDocumentSpecificationComponentsComponentFacesFaceVariablesVariable() {
        return new Document.Specification.Components.Component.Faces.Face.Variables.Variable();
    }

}
