//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.26 at 08:40:55 PM CDT 
//


package com.allflex.api.flexorderstatus;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.allflex.api.flexorderstatus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.allflex.api.flexorderstatus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderStatus }
     * 
     */
    public OrderStatus createOrderStatus() {
        return new OrderStatus();
    }

    /**
     * Create an instance of {@link ContainerNode }
     * 
     */
    public ContainerNode createContainerNode() {
        return new ContainerNode();
    }

    /**
     * Create an instance of {@link ContainerNode.Tags }
     * 
     */
    public ContainerNode.Tags createContainerNodeTags() {
        return new ContainerNode.Tags();
    }

    /**
     * Create an instance of {@link ContainerNode.Tags.TagSet }
     * 
     */
    public ContainerNode.Tags.TagSet createContainerNodeTagsTagSet() {
        return new ContainerNode.Tags.TagSet();
    }

    /**
     * Create an instance of {@link OrderStatus.Shipment }
     * 
     */
    public OrderStatus.Shipment createOrderStatusShipment() {
        return new OrderStatus.Shipment();
    }

    /**
     * Create an instance of {@link OrderStatus.Shipment.OrderLine }
     * 
     */
    public OrderStatus.Shipment.OrderLine createOrderStatusShipmentOrderLine() {
        return new OrderStatus.Shipment.OrderLine();
    }

    /**
     * Create an instance of {@link OrderStatus.Messages }
     * 
     */
    public OrderStatus.Messages createOrderStatusMessages() {
        return new OrderStatus.Messages();
    }

    /**
     * Create an instance of {@link ContainerNode.Tags.TagSet.Variable }
     * 
     */
    public ContainerNode.Tags.TagSet.Variable createContainerNodeTagsTagSetVariable() {
        return new ContainerNode.Tags.TagSet.Variable();
    }

    /**
     * Create an instance of {@link OrderStatus.Shipment.Address }
     * 
     */
    public OrderStatus.Shipment.Address createOrderStatusShipmentAddress() {
        return new OrderStatus.Shipment.Address();
    }

    /**
     * Create an instance of {@link OrderStatus.Shipment.OrderLine.TagManifest }
     * 
     */
    public OrderStatus.Shipment.OrderLine.TagManifest createOrderStatusShipmentOrderLineTagManifest() {
        return new OrderStatus.Shipment.OrderLine.TagManifest();
    }

}
