//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.26 at 08:40:50 PM CDT 
//


package com.allflex.api.flexorder;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.allflex.api.flexorder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderHeaderEmailListEIDInfo_QNAME = new QName("", "EmailListEIDInfo");
    private final static QName _OrderHeaderComments_QNAME = new QName("", "Comments");
    private final static QName _OrderHeaderEmailListTrackingInfo_QNAME = new QName("", "EmailListTrackingInfo");
    private final static QName _OrderHeaderPremiseID_QNAME = new QName("", "PremiseID");
    private final static QName _OrderHeaderEmailListError_QNAME = new QName("", "EmailListError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.allflex.api.flexorder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader createOrderHeader() {
        return new com.allflex.api.flexorder.OrderHeader();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.OrderHeader }
     * 
     */
    public OrderHeader createDocumentOrderHeader() {
        return new OrderHeader();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.OrderLineHeader }
     * 
     */
    public OrderHeader.OrderLineHeader createDocumentOrderHeaderOrderLineHeader() {
        return new OrderHeader.OrderLineHeader();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.OrderLineHeader.OrderLineMarkingDetail }
     * 
     */
    public OrderHeader.OrderLineHeader.OrderLineMarkingDetail createDocumentOrderHeaderOrderLineHeaderOrderLineMarkingDetail() {
        return new OrderHeader.OrderLineHeader.OrderLineMarkingDetail();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.OrderLineHeader.OrderLineCustom }
     * 
     */
    public OrderHeader.OrderLineHeader.OrderLineCustom createDocumentOrderHeaderOrderLineHeaderOrderLineCustom() {
        return new OrderHeader.OrderLineHeader.OrderLineCustom();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.OrderLineHeader.UserDefined }
     * 
     */
    public OrderHeader.OrderLineHeader.UserDefined createDocumentOrderHeaderOrderLineHeaderUserDefined() {
        return new OrderHeader.OrderLineHeader.UserDefined();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.UserDefined }
     * 
     */
    public OrderHeader.UserDefined createDocumentOrderHeaderUserDefined() {
        return new OrderHeader.UserDefined();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.OrderLineHeader }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.OrderLineHeader createOrderHeaderOrderLineHeader() {
        return new com.allflex.api.flexorder.OrderHeader.OrderLineHeader();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineMarkingDetail }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineMarkingDetail createOrderHeaderOrderLineHeaderOrderLineMarkingDetail() {
        return new com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineMarkingDetail();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineCustom }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineCustom createOrderHeaderOrderLineHeaderOrderLineCustom() {
        return new com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineCustom();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.OrderLineHeader.UserDefined }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.OrderLineHeader.UserDefined createOrderHeaderOrderLineHeaderUserDefined() {
        return new com.allflex.api.flexorder.OrderHeader.OrderLineHeader.UserDefined();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.UserDefined }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.UserDefined createOrderHeaderUserDefined() {
        return new com.allflex.api.flexorder.OrderHeader.UserDefined();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.OrderLineHeader.OrderLineMarkingDetail.Variable }
     * 
     */
    public OrderHeader.OrderLineHeader.OrderLineMarkingDetail.Variable createDocumentOrderHeaderOrderLineHeaderOrderLineMarkingDetailVariable() {
        return new OrderHeader.OrderLineHeader.OrderLineMarkingDetail.Variable();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.OrderLineHeader.OrderLineCustom.Variable }
     * 
     */
    public OrderHeader.OrderLineHeader.OrderLineCustom.Variable createDocumentOrderHeaderOrderLineHeaderOrderLineCustomVariable() {
        return new OrderHeader.OrderLineHeader.OrderLineCustom.Variable();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.OrderLineHeader.UserDefined.Field }
     * 
     */
    public OrderHeader.OrderLineHeader.UserDefined.Field createDocumentOrderHeaderOrderLineHeaderUserDefinedField() {
        return new OrderHeader.OrderLineHeader.UserDefined.Field();
    }

    /**
     * Create an instance of {@link Document.OrderHeader.UserDefined.Field }
     * 
     */
    public OrderHeader.UserDefined.Field createDocumentOrderHeaderUserDefinedField() {
        return new OrderHeader.UserDefined.Field();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineMarkingDetail.Variable }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineMarkingDetail.Variable createOrderHeaderOrderLineHeaderOrderLineMarkingDetailVariable() {
        return new com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineMarkingDetail.Variable();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineCustom.Variable }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineCustom.Variable createOrderHeaderOrderLineHeaderOrderLineCustomVariable() {
        return new com.allflex.api.flexorder.OrderHeader.OrderLineHeader.OrderLineCustom.Variable();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.OrderLineHeader.UserDefined.Field }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.OrderLineHeader.UserDefined.Field createOrderHeaderOrderLineHeaderUserDefinedField() {
        return new com.allflex.api.flexorder.OrderHeader.OrderLineHeader.UserDefined.Field();
    }

    /**
     * Create an instance of {@link com.allflex.api.flexorder.OrderHeader.UserDefined.Field }
     * 
     */
    public com.allflex.api.flexorder.OrderHeader.UserDefined.Field createOrderHeaderUserDefinedField() {
        return new com.allflex.api.flexorder.OrderHeader.UserDefined.Field();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailListEIDInfo", scope = com.allflex.api.flexorder.OrderHeader.class)
    public JAXBElement<String> createOrderHeaderEmailListEIDInfo(String value) {
        return new JAXBElement<String>(_OrderHeaderEmailListEIDInfo_QNAME, String.class, com.allflex.api.flexorder.OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Comments", scope = com.allflex.api.flexorder.OrderHeader.class)
    public JAXBElement<String> createOrderHeaderComments(String value) {
        return new JAXBElement<String>(_OrderHeaderComments_QNAME, String.class, com.allflex.api.flexorder.OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailListTrackingInfo", scope = com.allflex.api.flexorder.OrderHeader.class)
    public JAXBElement<String> createOrderHeaderEmailListTrackingInfo(String value) {
        return new JAXBElement<String>(_OrderHeaderEmailListTrackingInfo_QNAME, String.class, com.allflex.api.flexorder.OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PremiseID", scope = com.allflex.api.flexorder.OrderHeader.class)
    public JAXBElement<String> createOrderHeaderPremiseID(String value) {
        return new JAXBElement<String>(_OrderHeaderPremiseID_QNAME, String.class, com.allflex.api.flexorder.OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailListError", scope = com.allflex.api.flexorder.OrderHeader.class)
    public JAXBElement<String> createOrderHeaderEmailListError(String value) {
        return new JAXBElement<String>(_OrderHeaderEmailListError_QNAME, String.class, com.allflex.api.flexorder.OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailListEIDInfo", scope = OrderHeader.class)
    public JAXBElement<String> createDocumentOrderHeaderEmailListEIDInfo(String value) {
        return new JAXBElement<String>(_OrderHeaderEmailListEIDInfo_QNAME, String.class, OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Comments", scope = OrderHeader.class)
    public JAXBElement<String> createDocumentOrderHeaderComments(String value) {
        return new JAXBElement<String>(_OrderHeaderComments_QNAME, String.class, OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailListTrackingInfo", scope = OrderHeader.class)
    public JAXBElement<String> createDocumentOrderHeaderEmailListTrackingInfo(String value) {
        return new JAXBElement<String>(_OrderHeaderEmailListTrackingInfo_QNAME, String.class, OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PremiseID", scope = OrderHeader.class)
    public JAXBElement<String> createDocumentOrderHeaderPremiseID(String value) {
        return new JAXBElement<String>(_OrderHeaderPremiseID_QNAME, String.class, OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailListError", scope = OrderHeader.class)
    public JAXBElement<String> createDocumentOrderHeaderEmailListError(String value) {
        return new JAXBElement<String>(_OrderHeaderEmailListError_QNAME, String.class, OrderHeader.class, value);
    }

}
