//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.12 at 03:10:11 PM CDT 
//


package com.allflex.api.flexorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SkuName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="31"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PremiseID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="Template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserDefined" type="{}UserDefinedNode" minOccurs="0"/>
 *         &lt;element name="OrderLineCustom" type="{}VariablesNode" minOccurs="0"/>
 *         &lt;element name="OrderLineMarkingDetail" type="{}VariablesNode" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "skuName",
    "premiseID",
    "quantity",
    "unitOfMeasure",
    "template",
    "comment",
    "userDefined",
    "orderLineCustom",
    "orderLineMarkingDetails"
})
public class OrderLineHeader {

    @XmlElement(name = "SkuName", required = true)
    protected String skuName;
    @XmlElement(name = "PremiseID")
    protected String premiseID;
    @XmlElement(name = "Quantity")
    @XmlSchemaType(name = "unsignedShort")
    protected int quantity;
    @XmlElement(name = "UnitOfMeasure")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer unitOfMeasure;
    @XmlElement(name = "Template")
    protected String template;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "UserDefined")
    protected UserDefinedNode userDefined;
    @XmlElement(name = "OrderLineCustom")
    protected VariablesNode orderLineCustom;
    @XmlElement(name = "OrderLineMarkingDetail")
    protected List<VariablesNode> orderLineMarkingDetails;

    /**
     * Gets the value of the skuName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * Sets the value of the skuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuName(String value) {
        this.skuName = value;
    }

    /**
     * Gets the value of the premiseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremiseID() {
        return premiseID;
    }

    /**
     * Sets the value of the premiseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremiseID(String value) {
        this.premiseID = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUnitOfMeasure(Integer value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the userDefined property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedNode }
     *     
     */
    public UserDefinedNode getUserDefined() {
        return userDefined;
    }

    /**
     * Sets the value of the userDefined property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedNode }
     *     
     */
    public void setUserDefined(UserDefinedNode value) {
        this.userDefined = value;
    }

    /**
     * Gets the value of the orderLineCustom property.
     * 
     * @return
     *     possible object is
     *     {@link VariablesNode }
     *     
     */
    public VariablesNode getOrderLineCustom() {
        return orderLineCustom;
    }

    /**
     * Sets the value of the orderLineCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariablesNode }
     *     
     */
    public void setOrderLineCustom(VariablesNode value) {
        this.orderLineCustom = value;
    }

    /**
     * Gets the value of the orderLineMarkingDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLineMarkingDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLineMarkingDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariablesNode }
     * 
     * 
     */
    public List<VariablesNode> getOrderLineMarkingDetails() {
        if (orderLineMarkingDetails == null) {
            orderLineMarkingDetails = new ArrayList<VariablesNode>();
        }
        return this.orderLineMarkingDetails;
    }

}
